### PR TITLE
688: Added locales for Papiamento, Papiamentu, Norther Sotho, Maltese, Zulu, Fula (inclusive code)

### PR DESCRIPTION
**Pull request by c-schmitz**
... since they are currently missing

See #688.

### CODE REVIEW

**Comment by c-schmitz** [comment]
Added the following language locales:
-Northern Sotho
-Papiamento
-Papiamentu
-Maltese
-Zulu
-Fula

The one for Fula is a bit tricky - there is already a Fula entry but its language code (fuc) points to a spcific variety  only spoken in Senegambia and Mauritania. My entry  uses the inclusive code (ful) which covers all varieties. I think both are valid entries.

**Comment by ocean90** [comment]
Locales are managed by the WordPress Polyglots team, see https://make.wordpress.org/polyglots/handbook/translating/requesting-a-new-locale/.

Why do you need those locales?

**Comment by c-schmitz** [comment]
Because we are using these translations in our application.

**Comment by ocean90** [comment]
An application for WordPress? If not, then the wp_locale shouldn't be defined. Also new locales should use the ISO-3 code and we're using tabs for code indentation.

**Comment by c-schmitz** [comment]
No, not everything evolves around Wordpress :-).
We are using Glotpress for translations of LimeSurvey (http://www.limesurvey.org) - I would guess we have the biggest Glotpress installation outside a Wordpress scope.

See https://translate.limesurvey.org/projects/limesurvey-25/

We have been using the standalone Glotpress for a long time and I have been just converting stuff over to the Glotpress plugin and was fed up with adding locales manually.

**Comment by ocean90** [comment]
Closing in favour of #887 and #1047.

**Pull request closed without merging**
