### PR TITLE
Java i18n support: Clean empty comments and lines

### PR DESCRIPTION
**Pull request by IvanRF**

### CODE REVIEW

**Comment by toolstack** [comment]
This doesn't do anything the previous code didn't do...

**Comment by IvanRF** [comment]
You were adding `# No comment provided.` for every string, and double lines breaks.

**Comment by IvanRF** [comment]
thus increasing the generated file size with unneeded text

**Comment by toolstack** [comment]
Yes, that's for re-importing later, it should be there so it's more likely to match an existing string in comparison to a new string.

**Comment by IvanRF** [comment]
but re-importing should match "normal" Java .properties files, so those lines are not needed

**Comment by toolstack** [comment]
No, we only import from a existing .properties files, GlotPress does not scan source code.

**Comment by IvanRF** [comment]
? that's not what I say

**Comment by IvanRF** [comment]
when I mention Java files I was talking about .properties

**Comment by toolstack** [comment]
Image the following scenario, you create a translation, export it to your Java project and do some work on it.

You add additional strings to the properties file by hand and update some other translations, you then want to re-import it back in to GlotPress for other translators to work on.

The comments help us identify what's new and what's an update.

**Comment by IvanRF** [comment]
the comments? shouldn't you compare the existing keys against keys in the file?

**Comment by toolstack** [comment]
We do both to help match based on context (aka the comments) if it's available.

**Comment by IvanRF** [comment]
ah, I might be thinking in Java. I forget you use english text as the key

**Comment by toolstack** [comment]
It's also making sure we're consistent across the file formats if possible.

Closing the PR.

**Pull request closed without merging**
