### PR TITLE
203 Fix issue with permalink structures that did not have trailing slashes

### LINKED ISSUE #203: Can't access index page when permalinks have no trailing slash
Steps to reproduce:
- Set post permalinks to `/%postname%`
- Visit /glotpress

Current: Index page of WP loads
Expected: Redirect to /glotpress/projects

In https://github.com/deliciousbrains/GlotPress/blob/01bd9ae5874f42f6ae1196716f419f575f9f6ba1/gp-includes/router.php#L148-L153 we're comparing `/glotpress/` ($url_path) with `/glotpress` ($_SERVER['REQUEST_URI']).

### PR DESCRIPTION
**Pull request by toolstack**
… by adding user_trailingslashit() to gp_url_base_path() instead of ALWAYS appending a trailing slash.

Resolves #203.

### CODE REVIEW

**Comment by ocean90** [comment]
I really wish we can have some unit tests for this. So far I have this:

``` php
function test_index_when_permalinks_have_no_trailing_slash() {
    global $wp_rewrite;

    $wp_rewrite->init();
    $wp_rewrite->set_permalink_structure( '/%postname%' );
    $wp_rewrite->flush_rules();

    $this->go_to( gp_url_public_root() );
    $this->assertTrue( is_glotpress() );

    $wp_rewrite->init();
}
```

This test should fail without the PR, but it doesn't. :cry:

**Comment by toolstack** [comment]
Perhaps a simpler way would be just to validate that `gp_url_public_root()` doesn't have a trailing slash when it shouldn't with a simple `substr()` and an `assertEquals()` check?

**Comment by ocean90** [comment]
That's starting to get messy. We need a way to override the value of `GP_URL_BASE`, maybe a `gp_url_base` filter?

With the applied patch, permalinks set to `/%postname%` and `GP_URL_BASE` defined as `'/'` or `''` you will get a PHP notice:

```
Notice: Undefined index: path in /srv/www/glotpress-plugin/wordpress/wp-content/plugins/glotpress/gp-includes/url.php on line 14
Call Stack
#   Time    Memory  Function    Location
1   0.0023  241552  {main}( )   .../index.php:0
2   0.0040  242256  require( '/srv/www/glotpress-plugin/wordpress/wp-blog-header.php' ) .../index.php:17
3   0.7019  3149152 require_once( '/srv/www/glotpress-plugin/wordpress/wp-includes/template-loader.php' )   .../wp-blog-header.php:16
4   0.7019  3149200 do_action( string(17), ??? )    .../template-loader.php:12
5   0.7113  3425240 call_user_func_array:{/srv/www/glotpress-plugin/wordpress/wp-includes/plugin.php:525} ( string(12), array(1) )  .../plugin.php:525
6   0.7113  3425344 gp_run_route( string(0) )   .../plugin.php:525
7   0.7113  3425824 GP_Router->route( ) .../rewrite.php:81
8   0.7114  3426296 gp_url_path( string(23) )   .../router.php:148
```

That's because `gp_url_path()` assumes that there is always a path. Changing the return value to `isset( $parsed['path'] ) ? $parsed['path'] : '';` will fix the notice but now many links don't include the domain anymore:

``` html
<a href="http://projects/wordpress" title="Project: WordPress">WordPress</a>
```

**Comment by toolstack** [comment]
Just a quick test doesn't show up any links without the domain that I could see, did you see one somewhere?

**Comment by toolstack** [comment]
`gp_url_path()` never included the domain name so I wouldn't expect any breakage by returning ''.

**Comment by ocean90** [comment]
Yes, see the pasted HTML, that's from the projects overview. It's another function which doesn't expect an empty path.

**Comment by ocean90** [comment]
It breaks all relative URLs because of `gp_url)` which now returns "projects/wordpress" instead of "/projects/wordpress", the leading slash is missing.

**Comment by toolstack** [comment]
Hummm... I don't see that in my install with the GP_URL_BASE set to either '' or '/', I see:

`<a title="Project: test" href="/gp-plugin/projects/test">test</a>`

Which, while relative, is correct.

**Comment by ocean90** [comment]
It happens only if the permalink setting has no trailing slash.

**Comment by toolstack** [comment]
I've got that set but still don't see it.

**Comment by ocean90** [comment]
Hmm, if `gp_url_public_root()` returns no trailing slash `gp_url_path()` will return an empty string. In `gp_url()` the empty string gets used as the `$base` for `gp_url_add_path_and_query()`. `gp_url_add_path_and_query()` passes the `$base` to `gp_url_join()` and I can't really see something which is adding a leading slash there.

`gp_url_join( 'foo', 'bar' )` returns `foo/bar` for me.

**Comment by toolstack** [comment]
Is it a leading slash or a leading 'http://'?

I don't see a protocol portion being added to my links.

**Comment by ocean90** [comment]
Both? But yeah, it's adding a http:// in `gp_link_get()` because `esc_url( 'foo/bar' );` returns `http://foo/bar`.

**Comment by toolstack** [comment]
Ah I see why it doesn't fail for me, WP has to be in the root of the web site as well.

If instead of returning '' when there is no path we could return '/', which would address that case.

**Comment by ocean90** [comment]
Returning `/` in `gp_url_path()` doesn't feel right. If a URL has no path it should return no path. For example `parse_url( 'http://foo.bar', PHP_URL_PATH );` returns null too.

I think we have to fix `gp_url()` because of it's description

> Builds a URL relative to the GlotPress' domain root

**Pull request merged**
