### PR TITLE
Database is only updated on plugin activation

### PR DESCRIPTION
**Pull request by toolstack**
Resolves Issue #35.
Replaces PR #36.

### CODE REVIEW

**Comment by ocean90** [comment]
I think this should be in its own function and/or limited to the admin, like WordPress.

**Comment by toolstack** [comment]
In it's own function is fine (I didn't make one simply because at the moment it's very simple) but it shouldn't be limited to the admin as after an upgrade you could have a broken site if the upgrade functions don't run until the next time the admin logs in.

**Comment by ocean90** [comment]
https://wordpress.slack.com/archives/glotpress/p1444916566000115

**Comment by polevaultweb** [comment]
@bradt branch needs deleting [gardening]

**Pull request closed without merging**
