### PR TITLE
Add assets to own directory

### LINKED ISSUE #12: Move scripts and styles into Assets dir
Clean up the root dir a bit

### PR DESCRIPTION
**Pull request by polevaultweb**
Resolves #12

### CODE REVIEW

**Comment by A5hleyRich** [comment]
Reviewed, tested and merging

**Comment by bradt** [comment]
Remember. The primary goal here is to get this plugin working but change as little as possible. This wasn't necessary and is going to make merging changes from the standalone branch a huge PITA.

**Comment by polevaultweb** [comment]
Happy to revert if necessary?

**Comment by polevaultweb** [comment]
@bradt there's no reason I can't submit a similar patch upstream

**Comment by polevaultweb** [comment]
Patch submitted to standalone project https://glotpress.trac.wordpress.org/ticket/497

**Pull request merged**
