### PR TITLE
Idea: Use `current_user_can()` and custom capabilities

### PR DESCRIPTION
**Pull request by ocean90**
An idea for replacing `GP_User->can()`, see #5, #19.

The idea is to use the WP function [current_user_can()](https://developer.wordpress.org/reference/functions/current_user_can/) and the filters [map_meta_cap](https://developer.wordpress.org/reference/hooks/map_meta_cap/) and [user_has_cap](https://developer.wordpress.org/reference/hooks/user_has_cap/)  to provide an API for different permission systems like custom roles or the current permissions table from GP.

**tldr;** I thought WordPress has proper support for such a case, but it has not.
### Primary Capabilities

I have identified some primary capabilities. Some of them are used in this PR.
#### Projects
- gp_create_projects
- gp_edit_projects
- gp_delete_projects
#### Originals
- (gp_import_originals => gp_edit_projects)
#### Translation Sets
- gp_create_translation_sets
- gp_edit_translation_sets
- gp_delete_translation_sets
#### Translations
- gp_suggest_translations
- gp_approve_translations
- (gp_import_translations => gp_approve_translations)
#### Glossaries
- gp_create_glossaries
- gp_edit_glossaries
- gp_delete_glossaries
#### Glossary Entries
- gp_create_glossary_entries
- gp_edit_glossary_entries
- gp_delete_glossary_entries
- gp_import_glossary_entries

(The *_import caps are likely meta capabilities.)
### Meta Capabilities

The meta capabilities are used to check permissions on a specific object, like a project, a translation set or a glossary.
#### Projects
- gp_edit_project ($project)
- gp_delete_project ($project)
- gp_import_originals ($project)
#### Translation Sets
- gp_edit_translation_set ($set)
- gp_delete_translation_set ($set)
- gp_import_translations ($set)
#### Glossaries
- gp_create_glossary ($set)
- gp_edit_glossary ($glossary)
- gp_delete_glossary ($glossary)
#### Glossary Entries
- gp_create_glossary_entry ($glossary)
- gp_edit_glossary_entry ($glossary_entry)
- gp_delete_glossary_entry ($glossary_entry)
- gp_import_glossary_entries ($glossary)
## current_user_can()

Each  `$user->can()` can be replaced with `current_user_can()` and one of the capabilities from above. The capability name is more or less the action and the object type combined. The helper methods `GP_Route->can()`, `GP_Route->cannot_and_redirect()`, and `GP_Route->can_or_forbidden()` are changed to only support two arguments, the capability and the object ID.
Because we don't want to ship GP with custom roles which have these capabilities assigned we have to add them dynamically.
That's the fun part:
### map_meta_cap

With the `map_meta_cap` filter we can map our meta capabilities with the primary capabilities. But we can also map our primary caps with primary caps from WP, like `manage_options`. The PR does this for all capabilities for the _project_ object.
For `gp_approve_translations` or `gp_edit_glossary` I'm using the existing permissions system. This can be done for all the other capabilities too.

Note: You'll see a line `array_pop( $caps );`, that's because WP adds the original cap to the `$caps` array if there was no meta caps match, see https://github.com/WordPress/WordPress/blob/4.3/wp-includes/capabilities.php#L1415-L1416.
### user_has_cap

Now we have the required capabilities but the user still has non of the capabilities assigned. Via `user_has_cap` I'm going to add the capability to `$allcaps` if one of GP's capabilities exists in the meta `$cap` array. 
Yes, that's an dirty hack. It requires that _all_ capabilities _must_ be checked in `gp_map_meta_cap()`. If the user hasn't the correct permission you have to add `do_not_allow` to `$caps`.  (Also don't forget `array_pop( $caps );` per above). That's also important because `has_cap()` returns true if the list of caps is empty, see [#core-31518](https://core.trac.wordpress.org/ticket/31518).

---

That's all I have for now. I'd like to know what you think about this approach. Is there something I've missed? What can be done different to improve this idea?

(Note: The PR isn't finished, so please ignore the failing tests and such.)

### CODE REVIEW

**Comment by toolstack** [comment]
I've taken a look at this and it's an interesting approach but it still leaves me with the feeling that it's a solution looking for a problem.

There's a few things that come to mind:
- Adding complexity with no discernible benefit
- Hard coded property list
- Code runs for every current_user_can() including non GP related ones
- Combines action and object type in to a single data point

## Adding complexity

The code does a lot of work inserting itself between the existing database storage of the permissions and the testing of the permissions.  This adds a layer of complexity to the whole process.

This complexity makes following the permission code non-trivial to say the least.

Adding complexity to code is of course a prime way of creating unintended consequences and when it's security related that can be bad.  I don't see anything obviously wrong at the moment but with such an complex system it is prone to new errors in the future.

That could be forgiven if there was some huge benefit to the change, but at the end of the day this code does exactly what the current code does, just in a more round about way.

## Hard coded property list

This seems like something we should avoid if possible.  The above list is pretty complete from what I've seen, but that's only at the moment.

This could be an especially big problem for plugins as they would have to create their own meta_cap shims to deal with their permissions.

## Code runs for every current_user_can()

The hook code runs on every current_user_can() call that WordPress makes as well as any plugins.  That would seem like hundreds of extra calls to gp_user_has_cap() and gp_map_meta_cap().

That could be a pretty significant impact.

## Combine action and object type

Combining the two items in to a single capability name is something that has to be done to support the capabilities code in WordPress, but doing it early does limit the flexibility of the system.

Of course, directly calling current_user_can() necessitates this but perhaps a better way would be to create gp_current_user_can() that can take a more flexible properties list, allow for some extra filtering and perhaps do some of the extra leg work required later on.

## Summary

This code has only re-enforced my opinion that WordPress Roles and Capabilities are not a good fit for GP.  

The existing GP code is cleaner, easier to follow and more flexible.

A simpler approach may be called for with #5.  Pulling the permissions code out of GP_User in to it's own class along with any other functions that aren't replaceable with WP functions.  Then we can remove GP_User from the codebase.

As for #19, I think we should mark it as "won't fix" for now and review it if/when WP updates the Roles/Capabilities code.

**Comment by ocean90** [comment]
@toolstack Thanks for your feedback, much appreciated!

I agree with most of your points. As mentioned in the tldr; part I also agree that the way how I've used capabilities isn't really straightforward and can lead to potential (security) issues. 

> Combining the two items in to a single capability name is something that has to be done to support the capabilities code in WordPress, but doing it early does limit the flexibility of the system.

I disagree with that. I don't see much benefit in using "approve + translation-set" instead of "approve_translations". Currently GP doesn't store those either, it uses "approve + project|locale|set-slug" instead.

>  Pulling the permissions code out of GP_User in to it's own class along with any other functions that aren't replaceable with WP functions.

Yep, another idea would be to extend WP_User and add our custom methods. But it's not something I really want.

**Comment by toolstack** [comment]
> > Combining the two items in to a single capability name is something that has to be done to support the capabilities code in WordPress, but doing it early does limit the flexibility of the system.
> 
> I disagree with that. I don't see much benefit in using "approve + translation-set" instead of "approve_translations". Currently GP doesn't store those either, it uses "approve + project|locale|set-slug" instead.

The benefit of using them separately is really in what's possible with other permissions systems than what we have at the moment.  Combining them ties us to the same kind of big "switch" statement you had, or you have to re-parse them to break them up again.

It's kind of a moot point as I think we're mostly on the same page that it's not a very good fit.

I agree extending WP_User doesn't make much sense, after all the point was to get back to using the base WP class if possible.

I'm of two minds on what the next step is:
1. The Lazy Mind: It works now, why change anything?  As much as we have a custom user class, it doesn't really hurt anything and it works as is.
2. The Slightly Less Lazy Mind: Yes it works, but we should use WP_User so we don't run in to compatibility issues in future version of WP so let's create a separate class and get it done.

Early in the morning I lean towards 1, by the middle of the day I'm leaning towards 2 :wink:

**Comment by ocean90** [comment]
> The benefit of using them separately is really in what's possible with other permissions systems than what we have at the moment.

Okay, but we probably should review the current permissions, because using write/approve + translation-set for everything is meh, particularly with regard to #139. But that's stuff for another issue, which doesn't exist yet?

**Comment by toolstack** [comment]
Agreed, the current permissions are a mess and need to be looked at.

It's getting to be mid day again so I'm leaning towards 2 once more, so what do you think of this for the next steps:
- Create a new class to hold the permissions functions
- Create a new class (if required) to hold any other functions in GP_User that are not in WP_User
- Delete GP_User and replace any instances with the above classes as required
- Create a new issue to review the permissions for V1.1 along with #139
- Tag #19 as "won't fix" and review it again if WP Roles/Caps API changes or we come up with a brilliant idea at some point :smile:

**Comment by ocean90** [comment]
@toolstack Your steps make sense, although I don't think we need the second step. Will continue my work on #5.

@deliciousbrains/glotpress Please take a look at this PR,  in particular the recent comments. Thanks!

Edit: The GitHub team feature is the worst..

**Pull request closed without merging**
