### PR TITLE
Plugin prefix actions and filters

### PR DESCRIPTION
**Pull request by toolstack**
The GlotPress action/filters currently are a mix of "action_desc_here" and "gp_action_desc_here".

To avoid conflicts with other WordPress plugins, we should prefix all action/filters in GlotPress with "gp_" (that are GlotPress action/filters of course, not WordPress action/filters the plugin will use).

This resolves issue #33.

P.S. Ignore all commits in the PR prior to f944177, they're just step I had to take to get my repository in sync with deliciousbrains.

### CODE REVIEW

**Comment by polevaultweb** [comment]
@ocean90 needs wordpress-plugin-dbi merged in [gardening]

**Comment by toolstack** [comment]
wordpress-plugin-dbi merged.

**Comment by bradt** [comment]
If we merge this in, all the commits before f944177 will get merged in. I would probably create a new branch locally off the latest `wordpress-plugin-dbi` branch then cherry-pick the wanted commits from here.

**Comment by toolstack** [comment]
Replacing this PR with #44.

**Pull request closed without merging**
