### PR TITLE
Allow GP to take over the root URL on the frontend

### LINKED ISSUE #30: Allow GP to take over the root URL on the frontend
I think this can be achieved by allowing `define( 'GP_URL_BASE', '' );`. This may already work (I haven't tested it) but I doubt it.

### PR DESCRIPTION
**Pull request by bjork**
Properly formulate base URL path if the GP_URL_BASE constant is set empty. Add special handling for root URLs so WordPress recognizes them properly.

Fixes #30

### CODE REVIEW

**Comment by toolstack** [comment]
I've tested this on my local install and haven't found any issues.

Testing included using both root and non-root and default settings for the GP_URL_BASE constant and adding projects/translation sets as well as importing originals and importing/exporting translations (after updating the wpdb class with trunk as per issue #52).

One note is that after changing GP_URL_BASE the rewrite rules need to be re-register.

:+1: to merge.

**Comment by ocean90** [comment]
With this change GlotPress will try to handle _all_ URLs, means it's not possible to view custom pages or posts anymore because it returns a 404 error from GlotPress.
It should be possible to have at least pages still accessible. Thoughts?

**Comment by toolstack** [comment]
I'd say no, at least for version 1.0, taking over the root really means you want to use the plugin just like the old standalone install so you shouldn't be able to get to any other page but GlotPress.

Perhaps a future release could introduce supporting that kind of functionality as part of the WP theme support and better integration in to the admin pages?

**Comment by ocean90** [comment]
It looks like we only have to remove this line https://github.com/deliciousbrains/GlotPress/blob/d6d64318936885320a3e9412a3ce3c9ed28cd764/gp-includes/router.php#L188 to make this work.
Each GP route has it's own 404 handler if something doesn't exist.

**Comment by toolstack** [comment]
Pulling that line might have other implications, off the top of my head, if we're not in the root, a malformed URL inside the GlotPress namespace would fall back to the site's 404 instead of GlotPress's 404 page.

This might need to be a setable option?

**Comment by bjork** [comment]
@ocean90 Root of the site would still return WordPress front page, since without registering a WordPress rewrite rule '$' the index route of GlotPress will not get executed and so does not redirect to /projects. If we do that, it will be very hard to figure out if GlotPress is actually working at all for a person that does not know the URL structure.

**Comment by ocean90** [comment]
@bjork In my testing the root of the site was catched by the GlotPress rule and I got redirected to /projects.

@toolstack A URL like /projects/doesntexist is handled by GP and shows GlotPress' 404 page. Sadly /languages/doesntexist doesn't do the same because the route only matches existing locales. It's something which could be changed.
But I'm going to create another issue for this enhancement, I'm fine with moving this to future.

**Comment by ocean90** [comment]
@bjork It looks like you broke this PR with a recent merge in your branch. You should have created a new branch for this change first.

**Comment by bjork** [comment]
Sorry about that, not too familiar with this workflow yet. Should I create a new PR?

**Comment by ocean90** [comment]
@bjork Yes, please. When creating a branch, please use the following naming structure: (number of original GitHub issue)-followed-by-keywords-describing-the-project.

**Comment by bjork** [comment]
The new PR can be found here: #77

Closing this one.

**Pull request closed without merging**
