### PR TITLE
268: Add cancel link to import page.

### LINKED ISSUE #268: Add cancel link to import page
The import page doesn't have a cancel link and slightly funky formatting.

### PR DESCRIPTION
**Pull request by toolstack**
And cleanup formatting to be more consistent with the other pages.

Resolves #268.

### CODE REVIEW

**Comment by ocean90** [comment]
Can we avoid `javascript:history.back();` and use the project link instead?

**Comment by toolstack** [comment]
Yes, but all the other pages use the javascript so I kept it consistent.

**Comment by ocean90** [comment]
> but all the other pages use the javascript 

Right, but we should make an exception if the current consistency is _deprecated_. :wink:

**Comment by toolstack** [comment]
Who said it was deprecated? :wink:

**Pull request merged**
