### PR TITLE
Move profile related methods from `GP_User` to `GP_Route_Profile`.

### PR DESCRIPTION
**Pull request by ocean90**
See #5.

### CODE REVIEW

**Comment by toolstack** [comment]
Is the route really the right place for this from a OO perspective?  

I think they should be in a "thing" instead, either an existing one or a new one to handle these items.

**Comment by ocean90** [comment]
@toolstack A GP_Thing is connected to a table which we don't need here. This is just for data retrieving for the profile page.

**Comment by toolstack** [comment]
But it's not really a route either routes are associated with page generation...

**Comment by ocean90** [comment]
@toolstack I'm not creating a new route, just moving the methods to the existing route which is the only one who is using the data.

**Comment by toolstack** [comment]
Ok, sounds good.

**Pull request merged**
