### PR TITLE
218: Add an admin notice when permalinks are not enabled and disable

### LINKED ISSUE #218: Add warning and disable the plugin if permalinks are not set.
GlotPress requires permalinks to be set, so just like unsupported versions of WordPress, we should add an admin notice and disable the plugin if they don't exist.

### PR DESCRIPTION
**Pull request by toolstack**
Resolves #218.

### CODE REVIEW

**Comment by ocean90** [comment]
This change will break the unit tests because `GP_UnitTestCase` sets the permalinks to empty. https://github.com/GlotPress/GlotPress-WP/blob/master/tests/lib/testcase.php#L15

**Comment by toolstack** [comment]
Any idea why it does that?

**Comment by ocean90** [comment]
That's copied from https://github.com/aaronjorbin/develop.wordpress/blob/master/tests/phpunit/includes/testcase.php#L105-L107 because some tests are using [set_permalink_structure](https://github.com/aaronjorbin/develop.wordpress/blob/master/tests/phpunit/includes/testcase.php#L690)

But since the default value is empty anyway, we have to use another default one here. Maybe `/%year%/%monthnum%/%day%/%postname%/` which is from `wp_install_maybe_enable_pretty_permalinks()`?

**Comment by toolstack** [comment]
Yea, that seems reasonable.  I'll update the PR.

**Comment by toolstack** [comment]
I went with `'/%postname%'` instead as we use that in `test_urls.php` already.

**Comment by ocean90** [comment]
The tests are still failing.

**Comment by toolstack** [comment]
I've looked in to the tests and the problem is that the setUp() function (where we set the permalink) is called AFTER the check for the permalink structure in glotpress.php.

I'm not familiar enough with phpunit to know what the "proper" fix is, do we know anyone else more familiar with phpunit and the WordPress testing framework that might be able to help?

**Comment by toolstack** [comment]
So I've dug in to this quite a bit more and it comes down to a chicken and egg problem.

When the unit tests are run, the WP test setup drops all tables and recreates them, including wp_options.

Then the plugins are loaded and then the tests are run.

We need to hook in to the "install" process when the tables are re-created as WP's unit tests assume default values for everything.

Unfortunately there's no way to hook in at that level at this time and hooking in to WP's `init` or other location is too late as our plugin code will have already loaded.

There are three options I've thought of:
1. Create an MU plugin as part of the test suite that sets the permalink structure before GlotPress loads.
2. Detect that the tests are running in glotpress.php and do something about it.
3. Submit a patch to WP core to allow for some PHP code to be run after the tables are re-created.

I don't like number 1 as it requires another plugin and custom configuration for the test cases.

Number 2 is worse as it requires testing code in the production plugin.

The third option is probably the "correct" option, but I don't know how open core would be to this kind of change.

**Comment by toolstack** [comment]
As per the discussion on [Slack](https://wordpress.slack.com/archives/glotpress/p1455552470000029), using `$wp_tests_options` does what we need.

**Comment by ocean90** [comment]
Looks like setting the permalink structure through the filter breaks tests like `test_gp_url_public_root_has_a_trailing_slash_when_permalinks_have_a_trailing_slash` where we set another structure.

**Comment by toolstack** [comment]
Yep, it's because `gp_url_public_root()` passes back home_url() which doesn't pay attention to the permalink setting.

**Comment by toolstack** [comment]
Found the solution, user_trailingslashit() checks the $wp_rewrite->use_trailing_slashes variable to see if it should add the slash or not, so we have to make sure it's set correctly when we change the permalink structure for the test.

**Comment by toolstack** [comment]
Closing PR as it is for master instead of develop.

**Pull request closed without merging**
