### PR TITLE
Remove deprecated `assets/img/glotpress-logo.png`

### PR DESCRIPTION
**Pull request by PeterDaveHello**
This is not a code level PR, this is a lossless recompression via Google's zopfli, which can save the bandwidth to transfer the logo.

Save 2965 bytes, almost 40% of the origin size (4746 -> 1781 bytes)

Origin commands:
`$ zopflipng --iterations=1000 --lossy_transparent --splitting=3 --filters=01234mepb -y glotpress-logo.png glotpress-logo.png`

### CODE REVIEW

**Comment by toolstack** [comment]
That logo file is no longer used in the code, it's just there for historical reasons.

@ocean90 what do you think about just deleting it?

**Comment by PeterDaveHello** [comment]
Oops, if it was not used anymore, let's delete it.

**Comment by ocean90** [comment]
I'm fine with removing the logo.

**Comment by toolstack** [comment]
@PeterDaveHello can you update your PR to delete the file instead?  Thanks.

**Comment by PeterDaveHello** [comment]
Sure.

**Comment by PeterDaveHello** [comment]
Updated!

**Pull request merged**
