### PR TITLE
201 Filter the status code for GlotPress pages to avoid returning 404

### LINKED ISSUE #201: Wrong HTTP status
All GlotPress pages returns HTTP status 404.

`GP_URL_BASE` is set to '' (null).

Example: https://www.extendwings.com/translate/projects/

### PR DESCRIPTION
**Pull request by toolstack**
…headers to the browser.

Resolves #201.

### CODE REVIEW

**Comment by ocean90** [comment]
It's not just the status header, all the cache headers need to be removed as well. And `is_404()` shouldn't return true (haven't tested yet).

**Comment by toolstack** [comment]
I've updated the PR to deal with `is_404()`.

By the time GlotPress adds the 200, the following headers have been set:
- X-Powered-By: PHP/5.5.15 
- Content-Type: text/html; charset=UTF-8 
- Expires: Wed, 11 Jan 1984 05:00:00 GMT 
- Cache-Control: no-cache, must-revalidate, max-age=0 
- Pragma: no-cache

Which look fine for our purposes.

(One note is that the status header isn't in the list but that's because PHP's `headers_list()` doesn't return it, but it has been set to a 404, the PR overwrites it with the 200).

**Comment by ocean90** [comment]
Why are the headers set by `nocache_headers()`  fine for our purposes? Maybe I'm missing something..

**Comment by toolstack** [comment]
Because as an application we don't want the browser to cache our pages, otherwise something could change on the back end (another user edits a translation for example) and we wouldn't see the change with a refresh until the cache time expired.

**Pull request merged**
