### PR TITLE
Unit tests

### LINKED ISSUE #31: Unit tests - get 'em running with WP
...I'm assuming they need some tweaking to run as a plugin with WP.

### PR DESCRIPTION
**Pull request by gilbitron**
Resolves #31

I figured with lots more people now contributing to this project it made sense to get the CI integration up and running. If people are submitting PRs they should also be updating relevant tests. To run tests locally:

``` bash
$ ./tests/bin/run-unittests.sh <db-name> <db-user> <db-pass> [db-host] [wp-version] [drop-db]
```

### CODE REVIEW

**Comment by polevaultweb** [comment]
@gilbitron needs wordpress-plugin-dbi merged in [gardening]

**Comment by polevaultweb** [comment]
@gilbitron needs wordpress-plugin-dbi merged in [gardening]

**Comment by polevaultweb** [comment]
Happy to get this ready

**Comment by polevaultweb** [comment]
Currently ironing out some failing tests

**Comment by toolstack** [comment]
I tried it a few days ago and I had two tests fail, the android and XML exports.

**Comment by polevaultweb** [comment]
All fixed up now, good for a review

**Comment by toolstack** [comment]
I'm still getting the export errors, but that may be my environment and not the tests themselves.  I'm running XAMPP on Windows.

**Comment by polevaultweb** [comment]
@toolstack can you post the errors? Not seeing them myself, nor is Travis

**Comment by toolstack** [comment]
Here's the first error, the second is kind of long...

```
    <testsuite name="GP_Test_Format_Android" file="C:\xampp\htdocs\gp-plugin\wp-content\plugins\GlotPress-wordpress-plugin-dbi\tests\test_format_android.php" fullPackage="GP.Test.Format" tests="3" assertions="38" failures="1" errors="0" time="0.027107">
      <testcase name="test_export" class="GP_Test_Format_Android" file="C:\xampp\htdocs\gp-plugin\wp-content\plugins\GlotPress-wordpress-plugin-dbi\tests\test_format_android.php" line="20" assertions="1" time="0.009023">
        <failure type="PHPUnit_Framework_ExpectationFailedException">GP_Test_Format_Android::test_export
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 '&lt;?xml version="1.0" encoding="utf-8"?&gt;
 &lt;resources&gt;
    &lt;string name="normal_string"&gt;Just A Normal String&lt;/string&gt;
    &lt;string name="with_a_quote"&gt;I\'m with a quote&lt;/string&gt;
    &lt;string name="with_newlines"&gt;I\nhave\nnew\nlines&lt;/string&gt;
    &lt;string name="with_doublequotes"&gt;I have double "quotes"&lt;/string&gt;
    &lt;string name="with_utf8"&gt;баба ми омеси питка&lt;/string&gt;
    &lt;string name="with_lt"&gt;ти &amp;lt; аз&lt;/string&gt;
    &lt;string name="with_gt"&gt;аз &gt; ти&lt;/string&gt;
    &lt;string name="with_amps"&gt;аз &amp;amp; ти не сме &amp;amp;amp;&lt;/string&gt;
    &lt;string name="with_comment"&gt;баба&lt;/string&gt;
 &lt;/resources&gt;
 '

C:\xampp\htdocs\gp-plugin\wp-content\plugins\GlotPress-wordpress-plugin-dbi\tests\test_format_android.php:30
</failure>
      </testcase>
      <testcase name="test_read_originals" class="GP_Test_Format_Android" file="C:\xampp\htdocs\gp-plugin\wp-content\plugins\GlotPress-wordpress-plugin-dbi\tests\test_format_android.php" line="34" assertions="27" time="0.007874"/>
      <testcase name="test_read_translations" class="GP_Test_Format_Android" file="C:\xampp\htdocs\gp-plugin\wp-content\plugins\GlotPress-wordpress-plugin-dbi\tests\test_format_android.php" line="47" assertions="10" time="0.010210"/>
    </testsuite>
```

**Comment by toolstack** [comment]
Found the issue, it's the line endings in Windows, it's adding a \r\n instead of just a \n.

**Comment by toolstack** [comment]
In fact it's git's autolf handling that messes it up.  Perhaps we need a .gitattributes to turn off autolf for the test xml files.

**Comment by polevaultweb** [comment]
@toolstack glad you tracked that down. Shall we include as part of the PR, happy for you to commit to it

**Comment by toolstack** [comment]
I think it makes sense to add it here, I'm not that familiar with them but I'll poke at it a bit.

**Comment by toolstack** [comment]
I comitted a .gitattributes which solves the problem on Windows.

I think Travis CI is acting a little weird as all the tests excepts for PHP 5.6 passed and that seems an unlikely senerio to be caused by .gitattributes.

**Comment by toolstack** [comment]
I guess Travis CI resolved whatever was going on so everything has passed now.

**Comment by polevaultweb** [comment]
@toolstack :+1:

**Comment by ocean90** [comment]
This looks good, thanks everyone!

**Pull request merged**
