### PR TITLE
Fix for wrong seperator tag

### PR DESCRIPTION
**Pull request by chantalcoolsma**
Wrong HTML tag used. Therefor bullet point was bigger than the rest.

### CODE REVIEW

**Comment by toolstack** [comment]
I actually think that was intentional as a way to separate the filter drop downs from the single click actions.

**Comment by chantalcoolsma** [comment]
We get this sort behavior, however that bullet point doesn't change it enough.

schermafbeelding 2016-03-03 om 13 00 03

**Comment by toolstack** [comment]
I never said it was a good way to separate them :wink:.

Probably makes more sense to have Filter/Sort in a div and the quick actions in a separate div so they wrap correctly.

**Comment by chantalcoolsma** [comment]
Lets move this one to the future. I will think about a better solution.

**Comment by toolstack** [comment]
Sounds good, why don't you open an issue for it and we'll close this PR.

**Comment by chantalcoolsma** [comment]
Done

**Pull request closed without merging**
