### PR TITLE
Resolve unneeded redirects on GP generated links

### LINKED ISSUE #74: WordPress thinks every GlotPress page is_home, does not honor permalink setting
GlotPress links to URLs without trailing slashes, but WordPress redirects those URLs with trailing slashes. This happens even with permalinks set to have no trailing slashes. This is a problem because most clicks make two requests to PHP.

In `redirect_canonical()`, WordPress thinks `is_front_page()` is true. That is because `$wp_query->is_home` is set to true if no other type of page is detected. By setting that to false through a filter would probably solve the issue of redirects, assuming one sets the permalinks with no trailing slashes to match GlotPress's current behavior. But in addition to that, URLs GlotPress prints out should honor the permalink structure of WordPress.

This also effects the body class value, which states every GlotPress page is "home" and "blog" when they obviously are not.

### PR DESCRIPTION
**Pull request by bjork**
Stop WordPress from redirecting all GlotPress links without trailing slashes to ones with them.

Formulate links so that they respect the WordPress permalink setting whether links have trailings slashes or not.

Introduce `is_glotpress()` to determine if a page is handled by GlotPress. The location of the function should probably be revised though.

Fixes #74

### CODE REVIEW

**Comment by ocean90** [comment]
Getting a PHP notice on the admin dashboard:

```
Warning: array_key_exists() expects parameter 2 to be array, null given in /wp-content/plugins/glotpress/gp-settings.php on line 203
```

**Comment by ocean90** [comment]
`is_glotpress()` looks odd to me. Is the check for `DOING_AJAX` and `DOING_CRON` actually required?

**Comment by bjork** [comment]
Probably not. Those were copied over from `gp_run_route()`. I will remove those and test.

**Comment by bjork** [comment]
Could not find any issues with removing those.

**Comment by bradt** [comment]
@bjork This branch needs a refresh.

**Comment by toolstack** [comment]
@bjork: And it needs a merge again :wink:.

**Comment by ocean90** [comment]
See #193.

**Pull request closed without merging**
