### PR TITLE
Add doc blocks for hooks

### LINKED ISSUE #50: Add doc blocks for actions and filters
As per https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#4-hooks-actions-and-filters.

### PR DESCRIPTION
**Pull request by bjork**
Doc blocks in the works. Early feedback welcome.

Resolves #50.

### CODE REVIEW

**Comment by toolstack** [comment]
Shouldn't the @since line be version 0.1.0 instead of 1.0.0?

**Comment by bjork** [comment]
Yeah, I was going to ask about that. Since there are no real releases done of the plugin ever, I'm not sure what that 0.1 I see elsewhere refers to. I've now used 1.0.0 as a kind of a placeholder for a version number of the first release of the plugin.

**Comment by toolstack** [comment]
0.1.0 is the version used in the current code, while it's never been official released, it is the defacto version number for now I guess.

**Comment by DrewAPicture** [comment]
@ocean90 asked me to weigh in here.

The plugin is effectively a fork of GlotPress – treat it as a fork. When b2 was forked to become WordPress, all the function, class, hook, etc. versioning was reset based on the first WP _release_ version, 0.71. Any history prior to the first release of the fork is irrelevant.

Having independence from the original GlotPress versioning is important for the identity of the plugin, especially since it’s theoretically going in a different direction.

Now, as for whether to use 0.1.0 vs 1.0.0, go with whatever the first _release_ version of the plugin will be, regardless of what it is currently. If that's going to be 1.0.0, use 1.0.0.

**Comment by toolstack** [comment]
1.0.0 it is then.

**Comment by bradt** [comment]
:+1:

**Comment by bjork** [comment]
The hook documentation is now done – some hooks were skipped because they will be removed in another PR. It would greatly benefit from a second, detailed look. I am sure there are mistakes or at least the language could be improved.

Some notes I made of possible new issues to file:
- `backpress_set_cookie`/`gp_set_cookie` has a strange, special handling of boolean type response instead of a cookie array. Maybe a better way of controlling whether the cookies should be set would be to set the expires time to a past time, so that chaining of filters would not be affected. Not sure, but I think I noticed some other filters abusing the return value in somewhat similar fashion. Failed to make a note though.
- `gp_after_request` runs twice for no apparent reason.
- `gp_import_original_array` is called twice (explained in detail in the doc block). Probably a better way would be to have separate filters for the two different situations it is used for.
- `gp_original_import_max_length_diff` appears to have a bug. Judging by the name of the filter the filtered value is meant to define the maximum length difference in both directions, but the implementation seems to only control the times compared string can be shorter than the input string, but not the other way round.
- `gp_content()` and action `gp_content` are unused and thus a candidate for deletion.
- `gp_title()` is a confusing implementation as it is used for two different purposes.
- `gp_breadcrumb()` is similar to `gp_title()`.

All in all, I think GlotPress would greatly benefit from even more documentation on the source code level.

**Comment by toolstack** [comment]
@bjork 
- _set_cookie() only seems to be used in the gp_notices() function, which ignores the return value, did you see it somewhere else?
- gp_after_request actually only runs once, but the route class does include a call to it just in case.  You'll notice in route.php, the first line in after_request() returns without running it if $this->request_running is set, which is always true IF it's been called from router.php.
- gp_import_original_array, shouldn't it be possible to combine the two loops in to a single loop to avoid calling the filter twice?
- gp_original_import_max_length_diff looks ok, the abs() call will cover the longer and short conditions.
- gp_content() :+1: to delete.
- gp_title() pretty much mirrors wp_title(), perhaps we should replace gp_title() with wp_title()?
- There's no equivlient to breadcrumbs() in WP so no replacement, but the behaviour should be consitent I guess between them.

**Comment by bjork** [comment]
- `_cookie_set()`: Not sure what you mean with "ignores the return value". I was talking about the return value of the filter, not the function.
- `gp_after_request` does run twice, not sure why. Try this, if unconvinced:

```
add_action( 'gp_after_request', function ( $class, $method ) {
    error_log( 'class: ' . $class . ', method: ' . $method );
}, 10, 2 );
```
- On combining `gp_import_original_array` loops: Probably, but that would make the loop do too many things and thus make the code harder to follow. Also, the first loop one will go through all of the translation entries anyway and will apply the filters for each entry. It is very hard to see what is the reasoning behind the two calls, unless the latter one was mistakenly left renamed after a copy paste operation.
- I first thought so too about `abs()`. Here is a test case. Spoiler: The latter error_log prints out 'no'. :)

```
function gp_exeeds_max_length_diff( $input_length, $compared_string_length ) {
    if ( abs( ( $input_length - $compared_string_length ) / $input_length ) > 0.5 ) {
        return true;
    }
    return false;
}

error_log( 'should be true: ' . ( gp_exeeds_max_length_diff( 10, 20 ) ? 'yes' : 'no') );
error_log( 'should also be true: ' . ( gp_exeeds_max_length_diff( 20, 10 ) ? 'yes' : 'no') );
```
- [wp_title() will be deprecated in 4.4](https://make.wordpress.org/core/2015/10/20/document-title-in-4-4/). But since the GP template system will be deprecated in favor of the one in WordPress at some point, there probably is no need to dive deeper into this.

**Comment by toolstack** [comment]
- _set_cookie(), sorry, misunderstood which part you were talking about.  Agree the boolean check is a little strange, but setting the expiry in the past seems weird as well.  Perhaps returning an unset cookie name would make more sense?  Having said that though is there any reason to change it other than 'slightly weird'?
-  gp_after_request: I see why it's running twice, take a look in router.php:

```
$route->request_running = true;
// make sure after_request() is called even if we $this->exit_() in the request
register_shutdown_function( array( &$route, 'after_request') );
call_user_func_array( array( $route, $method ), array_slice( $matches, 1 ) );
$route->after_request();
do_action( 'gp_after_request', $class, $method );
$route->request_running = false;
```

$router->after_request() & do_action( 'gp_after_request') do the same thing, there should only be $router->after_request().
- gp_import_original_array, there should be a way to combine the two OR store the results from the first time through the loop so we don't have to re-call the filter.  Keeping it readable is important, but that can be done by carving some of the code out in to seperate functions, etc.
- gp_original_import_max_length_diff, your example works excatly like it should as the $input_length is used as the base divider.  So in the first example the second string is over 50% longer than the first, but in the second example the second string is exactly 50% longer than the first.  Try this instead:

```
error_log( 'should be true: ' . ( gp_exeeds_max_length_diff( 10, 20 ) ? 'yes' : 'no') );  // yes
error_log( 'should also be true: ' . ( gp_exeeds_max_length_diff( 10, 2 ) ? 'yes' : 'no') ); // yes
error_log( 'should also be true: ' . ( gp_exeeds_max_length_diff( 10, 5 ) ? 'yes' : 'no') ); //no
```
- wp_title() should then be replaced with whatever WP is replacing it with :wink:

**Comment by bjork** [comment]
- _set_cookie(): No, so let's drop this.
- gp_after_request: You want to create a ticket out of this?
- gp_import_original_array: There is no need to call the same filter twice currently. The second instance of calling it is done to a subset of originals. If that subset is needed to be targeted from a filter, then it should have a different name. I would just remove the filter now because the current implementation is clearly a bug. A filter for possibly added originals can very easily be added later if it is needed. I will create a ticket out of this where the issue can be discussed further.
- gp_original_import_max_length_diff: you are indeed correct, I have fixed the docs.
- gp_head: True, I will create a ticket.

**Comment by toolstack** [comment]
- gp_after_request: Yea a ticket makes sense.  I'll open one.
- gp_import_original_array() does need to be called twice since we could call the update() method in either location and if the filter has altered the data it needs to do it in both locations since we don't store the data between the loops.

**Comment by gilbitron** [comment]
@bjork This branch needs needs merging.

**Comment by toolstack** [comment]
Hi @bjork , as part of our move to the new repo this PR was closed when we merged back to "master" from "wordpress-dbi-plugin".  If you still want to get it merged, just create a new PR to the "master" branch of the GlotPress/GlotPress-WP repo.

Thanks and sorry of the inconvenience.

**Pull request closed without merging**
