### PR TITLE
Remove the $gpdb global and replace it with $wpdb

### PR DESCRIPTION
**Pull request by toolstack**
Resolves Issue #39.
Replaces PR #40.

### CODE REVIEW

**Comment by ocean90** [comment]
We should prefix the table keys with `gp_`: `$wpdb->gp_translations`, `$wpdb->gp_meta`, etc.

**Comment by toolstack** [comment]
Seems reasonable, though not directly related to the goal of this PR, I'll update the branch and PR.

**Comment by toolstack** [comment]
PR now adds the gp_ prefix to the $wpdb table names and updates the references in the rest of the code to use them.

**Comment by ocean90** [comment]
I thought we can do this without renaming `$table_basename` of each "thing" because of #10.
Can't we just change the constructor of `GP_Thing` to add the `gp_` prefix to each table name?

wp-settings.php does this already: https://github.com/deliciousbrains/GlotPress/pull/46/files#diff-4301a80ab0405c2c721d60ca52916d42R36

There is also a notice:

```
Notice: Undefined property: wpdb::$gp_users in /srv/www/glotpress-plugin/wordpress/wp-includes/wp-db.php on line 684
Call Stack
#   Time    Memory  Function    Location
1   0.0009  237400  {main}( )   .../index.php:0
2   0.0009  237856  require( '/srv/www/glotpress-plugin/wordpress/wp-blog-header.php' ) .../index.php:17
3   0.0009  238760  require_once( '/srv/www/glotpress-plugin/wordpress/wp-load.php' )   .../wp-blog-header.php:12
4   0.0014  239936  require_once( '/srv/www/glotpress-plugin/wp-config.php' )   .../wp-load.php:42
5   0.0014  242192  require_once( '/srv/www/glotpress-plugin/wordpress/wp-settings.php' )   .../wp-config.php:98
6   0.0132  1750112 include_once( '/srv/www/glotpress-plugin/wordpress/wp-content/plugins/glotpress/glotpress.php' )    .../wp-settings.php:191
7   0.0132  1751888 require_once( '/srv/www/glotpress-plugin/wordpress/wp-content/plugins/glotpress/gp-settings.php' )  .../glotpress.php:38
8   0.0143  2095776 require_once( '/srv/www/glotpress-plugin/wordpress/wp-content/plugins/glotpress/gp-includes/things/user.php' )  .../gp-settings.php:85
9   0.0143  2096000 GP_Thing->__construct( ??? )    .../user.php:312
10  0.0143  2097960 wpdb->__get( string(8) )    .../user.php:20
```

**Comment by toolstack** [comment]
I'll take a look at the notice and see what's going on.

The only concern with altering the constructor is that if anyone directly access the class it will the incorrect value.  Since the table_basename is set individually in each file now, I stuck with changing it in each file.

table_basename is NOT used to identify that actual name of the table (kind of counter intuitive) but the variable in $wpdb that contains the table name, so this is separate from #10.  At least as far as I can tell :wink:.

**Comment by ocean90** [comment]
Well, that's confusing. I'll have another look tomorrow.
But I just noticed that the standalone version has the `gp_` prefix for `table_basename`. So it looks like it got removed at some point.

**Comment by toolstack** [comment]
Found the issue with the notice, it only worked before because of a name collision between the user table in GP and WP.

I'll update it to point to the WP user table variable instead.

**Pull request merged**
