### PR TITLE
Add caching to things.

### LINKED ISSUE #114: Cache data of `GP_Project`s
`GP::$project->get()` should cache the data to prevent another SQL query for the same project ID.

### PR DESCRIPTION
**Pull request by toolstack**
Resolves #114.

### CODE REVIEW

**Comment by toolstack** [comment]
Humm... something broke on the tests, I'll track down what before it's ready for review.

**Comment by toolstack** [comment]
Resolved the failed tests by moving the cache from the things object and placing it in the GP object.

**Comment by ocean90** [comment]
With "cache" I meant object caching so we can benefit of cache drop-ins for persistent caching.

**Comment by toolstack** [comment]
Could you elaborate a bit more?  I'm not quite following what you mean.

**Comment by ocean90** [comment]
@toolstack See https://github.com/deliciousbrains/GlotPress/issues/114#issuecomment-155137737.

**Comment by toolstack** [comment]
Got it, will comment on the issue thread.

**Pull request closed without merging**
