### PR TITLE
Merge upstream changes as of Oct 14 2015

### PR DESCRIPTION
**Pull request by toolstack**
Merge upstream changes from GlotPress. 

Related to issue #11.
Replaces PR #43.

### CODE REVIEW

**Comment by ocean90** [comment]
This PR doesn't look proper. It includes a lot of "Merge branch 'master' into package" commits.

I'd also like to start to cherry-pick commits. So don't include BackPress related changes or the travis/coveralls commit.

**Comment by toolstack** [comment]
I agree it looks a little weird but it does contain the correct changes (I pulled out the conflicting changes from the commit).

I think we need to have a discussion about how we're going to merge future changes in as we move farther and farther away from the standalone install.

**Comment by ocean90** [comment]
We're going to cherry-pick commits.

**Comment by polevaultweb** [comment]
@bradt branch needs deleting [gardening]

**Pull request closed without merging**
